# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0298595152f5b8e84fdfe7d4d11ff7d58bc73ff3146d09dcac40cafdf0d152fb6119d6e78c79ce665b833c1f7f519450324e657e57a1bb6ff202989d3ab47b08

test:
  secret_key_base: f1e9cc3386786e25125cf3bc1a22dda94678eac2e195ea18c230a24d5c8cb40eb67e61b181f7558762d5f45db250acef3360c8eb9553accd82483bd181cdad05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
